### ISSUE TITLE
Allow to configure the download to path

### ISSUE THREAD

**Issue by laggedHero** [bjoernQ/unmock-plugin#13]
I've been using this library and I see that the robolectric jar is downloaded to the system tmp path.

From time to time it will be downloaded again (that's how tmp works outs... it's temporary). Not a big deal at my home, but quite troublesome at my job.

It's a low priority issue I known.

I could try to add this myself and send the PR in the coming weekend. But if you're already working on this one... there's no need for that.

Thanks

**Comment by bjoernQ** [comment]
Sounds like a valid requirement. I think I will implement this with the next version.

Hopefully I get some time to implement it next weekend.

For now you could use a workaround: Using a "file:///" url for the downloadFrom url pointing to a previously manually downloaded android-all.jar should avoid the troubles.

**Comment by bjoernQ** [comment]
0.3.6 now allows to configure the download directory, e.g.

downloadFrom 'https://oss.sonatype.org/content/groups/public/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar' to '/my_place/'

Please check if it works for you and close this issue. Thanks!

**Comment by laggedHero** [comment]
It's working. Sweet!

As a side note (for the docs?): the path should exist, or it's going to fail. (And I think that's a good thing!!).

Thanks!
