### ISSUE TITLE
Error : Execution failed for task ':app:unMock'

### ISSUE THREAD

**Issue by valllllll2000** [bjoernQ/unmock-plugin#16]
Hi,

I am using UnMockPlugin:0.3.6. I left everything as per default configuration, I am leaving out the configuration closure and downloadFrom . Some days I get this error message, like at every compile : 
Error:Execution failed for task ':app:unMock'.
> error in opening zip file
his sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

I am using android studio 1.4 (this also happened with 1.3) with Ubuntu 14.04 and javac 1.7.0_80, the oracle one. I do have internet connection. 
I am not sure if this is a bug or there is something I can add to build file to fix it. 
Thanks

**Comment by bjoernQ** [comment]
Hi,

seems that the plugin tried to download the JAR but it wasn't completely downloaded. Now you have a broken JAR file in the temp directory.

The easiest way to solve this is to find the file in temp and delete it. During the next build the JAR gets downloaded again and the problem should vanish.

Hope this helps.

**Comment by valllllll2000** [comment]
Hi,

thanks for the quick reply but I do not think it is correct. I have tried doing find -name android-all*
in command line in the project directory and it did not find any file with such name. Is there a way to set this to not re-download this file each time and use some local file?

**Comment by bjoernQ** [comment]
The file is not in downloaded to the project directory but to the tempdir. So you should try "find -name *android-all*" in the tempdir. The real file name is something very long (containing the full URL with special characters replaced by "_")

Another option is to have a configuration closure and force the downloaded file to be placed in a different directory like this
```
downloadFrom 'https://oss.sonatype.org/content/groups/public/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar' to '/yourdirectory_to_download_to'
```

Just replace /yourdirectory_to_download_to into your desired directory.

**Comment by valllllll2000** [comment]
Thanks a lot for your help, I have found the file in the tmp folder of the PC, the name of the file is actually https___oss.sonatype.org_content_groups_public_org_robolectric_android-all_4.3_r2-robolectric-0_android-all-4.3_r2-robolectric-0.jar. Next time I get the error I will try deleting the file.

**Comment by swengconsultant** [comment]
Hi,

I am getting this same error. I have found the 4.3*robolectric*jar file in my ~/.m2/respository directory and have deleted this. I am using AS and gradle on Linux and when I rebuild which involes app:UnMock task it does not seem to download the jar and I still get the same error. 

Any ideas?

Thanks
