### ISSUE TITLE
Upload to Maven Repository

### ISSUE THREAD

**Issue by klassm** [bjoernQ/unmock-plugin#2]
Hi,
trying to find the unmock-plugin in search.maven.org results in no entries. You might consider uploading your plugin in some arbitrary maven repository.
Matthias

**Comment by klassm** [comment]
Just found out you need to add jcenter() as repository. You might want to update your readme to include the build repository.

**Comment by bjoernQ** [comment]
Hello,

it's available on jCenter. Why do you need it to be available on Maven
Central? (Just curious about that - since I thought jCenter should be the
easiest for most devs since it's the default repository).

Best,
Björn

**Comment by bjoernQ** [comment]
Your mail came in while I was typing my last reply ..... good point about
mentioning jcenter in the readme.

Thanks
Björn


On Sat, Feb 28, 2015 at 11:46 AM, Bjoern Quentin <bjoern.quentin@mobile-j.de
> wrote:

> Hello,
>
> it's available on jCenter. Why do you need it to be available on Maven
> Central? (Just curious about that - since I thought jCenter should be the
> easiest for most devs since it's the default repository).
>
> Best,
> Björn
>

**Comment by klassm** [comment]
You're welcome :-). And thanks for your plugin. Now all my tests work again!

**Comment by bjoernQ** [comment]
Added a hint to the README.md
