### ISSUE TITLE
"Error in opening zip file" when including the plugin twice

### ISSUE THREAD

**Issue by johnjohndoe** [bjoernQ/unmock-plugin#23]
I am working on an Android project which uses Git as the version control system. Parts of the code are maintained in a Git submodule named _commons_ in order to being used by other application projects as well. The _commons_ submodule as well as the _application_ module contain unit tests. In the past, I added the _unmock-plugin_ version 0.5.0 in the _commons_ submodule for being used by a subset of the tests. Tests in the _commons_ submodule **pass**.

```
.
├── commons
│   ├── build.gradle // has the unmock-plugin
│   └── src
├── app
│   ├── build.gradle
│   ├── src
```

``` groovy
// commons submodule build.gradle

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "de.mobilej.unmock:UnMockPlugin:0.5.0"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'de.mobilej.unmock'

android { /* ... */ }

unMock {
    keep "android.database.DatabaseUtils"
    keepStartingWith "android.text."
    keepStartingWith "com.android.internal.util."
    keepStartingWith "org.ccil.cowan.tagsoup."
}
```

Now, I want to reference the _unmock-plugin_ in the _application_ module as well since a subset of test there also require mocking parts of the Android framework.

```
.
├── commons
│   ├── build.gradle // has the unmock-plugin
│   └── src
├── app
│   ├── build.gradle // has the unmock-plugin
│   ├── src
```

``` groovy
// application module build.gradle

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath "de.mobilej.unmock:UnMockPlugin:0.5.0"
    }
}

apply plugin: 'com.android.application'
apply plugin: 'de.mobilej.unmock'

android { /* ... */ }

unMock {
    keep "android.net.Uri"
}
```
### Shell / Jenkins

Running the tests of the _application_ module **fails** with the following error message:

> Execution failed for task ':commons:unMock'.
> error in opening zip file

Please note, that tests are executed by invoking Gradle on the shell. I noticed this when running the tests on Jenkins.
### Android Studio

In contrast, when I manually run the tests of the _application_ module they **pass**. If I run the tests of _commons_ submodule they **fail**.
- app ✅ 
- commons ❌

**Comment by bjoernQ** [comment]
At first it sounds similar to https://github.com/bjoernQ/unmock-plugin/issues/16 but it doesn't make sense given the observations you made using Android Studio.

I successfully use similar setups but in my case the library projects and the app projects share the same root build.gradle defining the buildscript clause.

Maybe it's possible to share the output of gradlew <testTask> --stacktrace ?

I will try to setup some test code with the same setup ( each module defining the buildscript clause individually ) to see if this is the cause of the problem.

**Comment by bjoernQ** [comment]
Just tried to recreate your setup but it works for me. Maybe there is still a difference in the project setup I don't see from the given information. If you don't mind could you create a sample showing the problem so I am able to reproduce the problem on my system?

**Comment by johnjohndoe** [comment]
> Maybe you can also try to have a root build.gradle defining the buildscript clause?

I temporarily moved the `classpath "de.mobilej.unmock:UnMockPlugin:0.5.0"` dependency declaration into the root _build.gradle_ file. Then I rerun the tests with the following result:

### Running tests in Android Studio

* commons ❌ 
* app ✅ 

### Running test in the shell

* commons ✅ 
* app ✅

**Comment by bjoernQ** [comment]
That's a surprising result.

I tried to reproduce your observations without success. I am using Android Studio 2.2.2, Gradle plugin 2.2.2, Gradle (wrapper) 2.14.1 - everything works as expected (command line and from inside Android Studio)

In the past I also observed strange behavior in Android Studio (not with Unmock but other dependencies) when Studio wasn't able to pick up changed/added dependencies and the only way to solve it was removing all the .idea folders and doing a fresh import of the project. That might explain the problems in Studio but not the previous observations on the command line.

**Comment by johnjohndoe** [comment]
I am using Android Studio 2.1.3 for this project, Gradle plugin 2.1.3, Gradle wrapper 2.14.1.
I will try reimporting the sources after cleaning *.iml files and the *.idea folder.

**Comment by bjoernQ** [comment]
Any progress on your side?

**Comment by johnjohndoe** [comment]
Sorry for the delay (I became sick). I did a clean import into Android Studio 2.1.3. Running the tests gives the same unsatisfying results.

**Comment by bjoernQ** [comment]
Hope you are well again. What is the exact reason of the failing tests? Do the tests don't get the unmocked classes or does it fail in the UnMock plugin code?

I attached a project which is my try to reproduce the problem (without success). Maybe you can import the project and see if it fails, too. If not we might be able to figure out the difference in your setup.

[App.zip](https://github.com/bjoernQ/unmock-plugin/files/560352/App.zip)

One thing I remember as a problem in Studio is that the IDE creates a wrong classpath when using different compile / target SDKs for the modules. (I raised a bug for Studio which is now marked as fixed but the bug tracker doesn't give any indication of the fixed version)

**Comment by johnjohndoe** [comment]
Here is one failure output:

> java.lang.RuntimeException: Method sqlEscapeString in android.database.DatabaseUtils not mocked. See http://g.co/androidstudio/not-mocked for details.

I tried your project. There tests do succeed for me, too. I try to figure out what differs to my project.

**Comment by johnjohndoe** [comment]
I added unit test to the `app` and `common` modules. Now test in `common` module **fail**.

* [app-with-failing-unit-test-in-common-module.zip](https://github.com/bjoernQ/unmock-plugin/files/560609/app-with-failing-unit-test-in-common-module.zip)

**Comment by bjoernQ** [comment]
With your modifications I can now reproduce the problem. Studio doesn't include the unmocked-android.jar in the classpath while it works when running the tests from Gradle. I don't have any idea yet why it happens in this setup while it definitely works in other projects. (The common.iml file looks good and contains the unmocked-android.jar)

**Comment by johnjohndoe** [comment]
Do you think this is a IDE issue which should be filed?

**Comment by bjoernQ** [comment]
After some investigation it seems like it is an IDE bug - but I need to break it down to something more general and it seems to be a problem in the core IDE (IntelliJ) - not in the Android extension.

But I'm not completely sure. However if it runs from the command line it should run the same from inside Android Studio. Quite an interesting issue.

**Comment by johnjohndoe** [comment]
Thank you for the effort. - I believe the IntelliJ team will like to play around with an example project. Feel free to use the one I posted. If you file a bug please link it here so we can keep track of it.

**Comment by bjoernQ** [comment]
Maybe I have found a workaround for the Android Studio problem. I'll check it tomorrow - it's a bit late now here in Germany.

**Comment by bjoernQ** [comment]
I was able to isolate the problem and I filed a bug for Android Studio - if it's really a problem in the core IDE I guess the Android Tools team will forward it to the IntelliJ team.

https://code.google.com/p/android/issues/detail?id=226680

I will create a version of UnMock with a work around for the issue.

**Comment by bjoernQ** [comment]
0.5.1 should solve the problem with Android Studio - let me know if it works for you or if there are any remaining issues.

**Comment by johnjohndoe** [comment]
Reference to #24.

**Comment by johnjohndoe** [comment]
Looks good to me. Thank you for your support!
