### ISSUE TITLE
[Supprot]The specified API level can not be greater than 21

### ISSUE THREAD

**Issue by lijunguan** [bjoernQ/unmock-plugin#25]
downloadFrom 'https://oss.sonatype.org/content/groups/public/org/robolectric/android-all/6.0.0_r1-robolectric-0/android-all-6.0.0_r1-robolectric-0.jar'
After API 21,com.android.internal.util.ArrayUtils.java implemention has changed,
Dependencies：Sparse***Array .java  ->com.android.internal.util.ArrayUtils  ->dalvik.system.VMRuntime  
Even if   "dalvik.system.VMRuntime " is mocked, it will crash  at initialize Sparse***Array.

**Comment by bjoernQ** [comment]
I will have a look into this and update the sample project to API level 21.

**Comment by bjoernQ** [comment]
I updated the sample project. It should work using version 0.6.0 of the plugin which adds some magic to handle some VMRuntime and java.lang.System method calls internally.
