### ISSUE TITLE
Not possible to unmock parcel

### ISSUE THREAD

**Issue by barrywe7** [bjoernQ/unmock-plugin#26]
If I include android.os.Parcel in the gradle file testObject.writeToParcel(parcel, 0) still ends up with no data included in the parcel object. Is it possible to include parcels or does the native implementation prevent this?

**Comment by bjoernQ** [comment]
Unfortunately Parcel depends on native code - what I did is mocking it with PowerMock which was good enough for my UnitTests.

**Comment by SKART1** [comment]
Why do not use pure java realization? Parcel is something as map of maps?
May be create repo with mocks for standard android classes such as parcelable?


P.S. Robolectric in it`s own runner allows to test parcellable

**Comment by barrywe7** [comment]
Thanks for suggestions @bjoernQ @SKART1 I'll checkout both those options

**Comment by bjoernQ** [comment]
@barrywe7 I added a simple test mocking Parcel here https://github.com/bjoernQ/unmock-plugin/blob/master/example/src/test/java/de/mobilej/testproject/ParcelTest.java

@SKART1 Actually a good idea to create a collection of mock utilities. I'd like to start this as soon as I get some spare time.
