### ISSUE TITLE
Unmocked jar not found with Gradle 4.0, Android plugin 3.0 and Kotlin support

### ISSUE THREAD

**Issue by xsveda** [bjoernQ/unmock-plugin#33]
Gradle: `4.0-milestone-1`
Android plugin: `3.0.0-alpha1`
Kotlin: `1.1.2-4`
UnMock: `0.6.1`

When a project with above configuration has a Kotlin support enabled then the `unMock` gradle task doesn't run as a preparation for unit tests though Kotlin is not used and unit test is in plain Java.
The problem is that Kotlin compile task name `compileDebugUnitTestKotlin` does not match UnMock reg-exes.

Minimal working example: [UnMockPlugin30issue.zip](https://github.com/bjoernQ/unmock-plugin/files/1021412/UnMockPlugin30issue.zip)

**Comment by bjoernQ** [comment]
Thanks for opening this issue. I can reproduce the reported issue and the upcoming version should fix this.

**Comment by bjoernQ** [comment]
0.6.2 works for me with your example, reopen if it doesn't work for you - if it works I'd be happy to hear about it

**Comment by vRallev** [comment]
I can confirm that the new version works. Thanks!

**Comment by xsveda** [comment]
@bjoernQ It works, thank you for such quick fix!
