### ISSUE TITLE
Could not find method unMock() for arguments ...

### ISSUE THREAD

**Issue by OleksandrKucherenko** [bjoernQ/unmock-plugin#36]
Got an issue (before it works fine):
```
Could not find method unMock() for arguments [build_a23gdqvug8bcmrcd2asmg611q$_run_closure5@5d9e562b] on project ':app' of type org.gradle.api.Project.
```

Latest Gradle:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-rc-2-bin.zip
```

In build.gradle (root project):
```
        /* UnMock, https://github.com/bjoernQ/unmock-plugin */
        classpath 'de.mobilej.unmock:UnMockPlugin:0.6.2'
```

In app/build.gardle:

```
    apply plugin: 'de.mobilej.unmock'

    unMock {
        keepStartingWith "android.text.TextUtils"
        keep "android.net.Uri"
        keep "android.os.Bundle"
        /* Keep JSON parser available as a part of unit tests */
        keepStartingWith "org."
    }

```

**Comment by bjoernQ** [comment]
The error indicates that the plugin wasn't applied but obviously you apply it and I guess you already tried a clean build.

Did you changed anything in that project or is it a new setup project? Or is it a project wich was working before and stopped working suddenly out of the blue?

Any difference in behavior if you try it from Android Studio or from command line?

Maybe you can do a clean build on the command line and paste the output here?

**Comment by johnjohndoe** [comment]
@OleksandrKucherenko Please change the title of your issue to the error message "Could not find method unMock() for arguments ...".

**Comment by OleksandrKucherenko** [comment]
Updated only gradle from v3.5 to 4.0-rc2

**Comment by OleksandrKucherenko** [comment]
Log from gradle:

```
./gradlew clean cleanBuildCache --debug
```

[debug.log.zip](https://github.com/bjoernQ/unmock-plugin/files/1067837/debug.log.zip)

**Comment by OleksandrKucherenko** [comment]
```
12:39:39.107 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Apply plugin de.mobilej.unmock to project ':app'' started
12:39:39.107 [WARN] [org.gradle.api.Project] Make sure to use Android Gradle plugin version 1.1.0 (or newer)
12:39:39.107 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Apply plugin de.mobilej.unmock to project ':app''
12:39:39.107 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Apply plugin de.mobilej.unmock to project ':app'' completed
```

this is the only one umock message that means something

**Comment by bjoernQ** [comment]
Oh I guess you are not using the Android Gradle Plugin 3.0-x ?

When using Gradle 4.x the UnMock plugin assumes you are using Android Gradle Plugin 3.x

Unfortunately migration to 3.x involves a bit more work: https://developer.android.com/studio/preview/features/new-android-plugin-migration.html

**Comment by OleksandrKucherenko** [comment]
no, plugin version is GRADLE_PLUGIN=2.4.0-alpha7

**Comment by OleksandrKucherenko** [comment]
Any workaround?! or maybe a new version with a fix?

**Comment by bjoernQ** [comment]
Unfortunately it seems to be impossible to get the version of the Gradle plugin. There is no API to get it in the plugin and I wasn't able to get it from Gradle.

I will have a look at this.

**Comment by bjoernQ** [comment]
Please give 0.6.3 a try - it should fix your problems

**Comment by OleksandrKucherenko** [comment]
👍

**Comment by OleksandrKucherenko** [comment]
works perfectly well!!! Thanks
