### ISSUE TITLE
UNMOCK does not copy data files inside the jar

### ISSUE THREAD

**Issue by OleksandrKucherenko** [bjoernQ/unmock-plugin#42]
```
        keepStartingWith "android.icu.impl.data.icudt58b."
```

package contains a resources data files. They are not copied during the processing. as result - class Currency cannot be un-mocked.

> java.util.MissingResourceException: Could not find the bundle android/icu/impl/data/icudt58b/curr/en_US.res

**Comment by bjoernQ** [comment]
should work with 0.6.5 - there is a new test covering this in "examplelib"
