### ISSUE TITLE
java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by ligi** [bjoernQ/unmock-plugin#44]
currently I am getting:

```
⋊> ./gradlew clean build                                                 16:40:12
> Task :app:unMock FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:unMock'.
> java.util.zip.ZipException: error in opening zip file

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
4 actionable tasks: 3 executed, 1 up-to-date

```

I think the zip file is corrupted as I aborted a previous build. I had this once before and have to find the file again now. 
Would be great if the plugin re-downloads on this exception - could provide a better developer experience.

**Comment by ligi** [comment]
see also #30 

removing .gradle/caches did not work for me - I had to remove:

/tmp/https___oss.sonatype.org_content_groups_public_org_robolectric_android-all_4.3_r2-robolectric-0_android-all-4.3_r2-robolectric-0.jar

**Comment by bjoernQ** [comment]
Thanks for your suggestion to automatically delete and redownload if opening the JAR fails. I'll add that.

It seems you are still using the "old" way of declaring the dependency. If you upgrade to a recent version of the plugin (i.e. "downloadFrom" or the default)

If you configure a dependency like:
```
dependencies {
    // dependency to android-all to use
    unmock 'org.robolectric:android-all:4.3_r2-robolectric-0'
}
```

The plugin will use Gradle's dependency management to download the artifact. Gradle's dependency management is much more robust and the preferred way to do things now. Maybe I should default to it for the next version.

So the action points for me for the next version:
- default to use Gradle's dependency management if nothing is configured (not downloadFrom and not the unmock dependency)
- retry download if the JAR is corrupted
- give a deprecation message if using an explicit "downloadFrom"

Thanks for pointing out this inconvenience.

**Comment by bjoernQ** [comment]
Since all the 'downloadFrom' stuff is really bad and legacy it will be removed with 0.7.0

Gradle's dependency management is really good and should be the way to go form 0.7.0 on.
