### ISSUE TITLE
Changing build.gradle file in any way will cause unMock task to run again

### ISSUE THREAD

**Issue by matejdro** [bjoernQ/unmock-plugin#46]
Steps to reproduce the bug:

1. Download [unmockdemo.zip](https://github.com/bjoernQ/unmock-plugin/files/2584422/unmockdemo.zip) and extract it somewhere
2. Run `./gradlew assembleDebug` and wait for it to do compile for the first tme
3. Run `./gradlew assembleDebug` again. Note that build is very fast since there were no changes to the source or configuration - everything is UP-TO-DATE)
4. Add newline anywhere in `app/build.gradle`
5. Run `./gradlew assembleDebug` again. Note that unMock task will run, even though it has no reason to run (there were no changes that would require it to refresh itself)

**Comment by bjoernQ** [comment]
Hi!
It's the currently implemented behavior: the plugin checks if the generated JAR is older than the timestamp of the build file.

But I see that this could be optimized and would be helpful when often changing the build file.

It's a feature for an upcoming version.

Thanks!
