### ISSUE TITLE
Support Gradle Build Cache

### ISSUE THREAD

**Issue by drewhannay** [bjoernQ/unmock-plugin#47]
The tasks from this plugin should be enhanced to support the Gradle Build Cache:
https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details

**Comment by bjoernQ** [comment]
Thanks for the suggestion - I'll look into it

**Comment by drewhannay** [comment]
Would you be open to a pull request if I can get it working? I think fixing this would also necessarily fix #46 as well

**Comment by bjoernQ** [comment]
I'd be happy to receive a PR for that - unfortunately I'm currently busy with some other things so doing it myself would take some time.

Looking forward to your PR

**Comment by drewhannay** [comment]
Here you go! :)

https://github.com/bjoernQ/unmock-plugin/pull/48

**Comment by bjoernQ** [comment]
Merged and released. Thanks again.
