### ISSUE TITLE
How to create a snapshot of unmock for testing changes?

### ISSUE THREAD

**Issue by drewhannay** [bjoernQ/unmock-plugin#50]
I'd like to test some changes to unmock with my app before submitting a pull request, but I can't figure out how to make a snapshot and use it. Any tips?

**Comment by bjoernQ** [comment]
One way would be (if your app doesn't have a `buildSrc` directory) could be to copy (or better symlink) the `buildSrc` of the unmock plugin project to your project.

Another way would be to change the pluginVersion in `buildSrc/build.gradle` to e.g. `0.7.2-SNAPSHOT`. You'll also need to add the line `group 'de.mobilej.unmock'`

Now you can run `gradlew publishToMavenLocal` and publish this version to your local Maven repository.

In you app you need to add `mavenLocal()` repository and should be able to pick the locally published snapshot version.

Hope this helps and works for you

**Comment by drewhannay** [comment]
Thanks, that works! The piece i was missing is that you need to be inside the `buildSrc` directory and run `../gradlew publishToMavenLocal`. If you try to run from the project root, it fails.
