### ISSUE TITLE
Unmock plugin doesn't use lazy task APIs of gradle 4.9+

### ISSUE THREAD

**Issue by stephanenicolas** [bjoernQ/unmock-plugin#51]
Gradle 4.9 introduced Task Configuration Avoidance:
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

Umock doesn't use the new APIs and trigger the creation of most of tasks for most variants.

I believe the only things to change would be : 
* https://github.com/bjoernQ/unmock-plugin/blob/master/buildSrc/src/main/groovy/de/mobilej/unmock/UnMockPlugin.groovy#L45 -> use register to create the task lazily
* https://github.com/bjoernQ/unmock-plugin/blob/master/buildSrc/src/main/groovy/de/mobilej/unmock/UnMockPlugin.groovy#L67 -> use withType(JavacCompile/KotlinCompile ?).configureEach
* Actually, there is something better to do than the previous point: https://github.com/bjoernQ/unmock-plugin/blob/master/buildSrc/src/main/groovy/de/mobilej/unmock/UnMockPlugin.groovy#L46 could use variants, get their compiler tasks provider and depend on it. It would remove the afterEvaluate clause that is a bit dirty... ;)

The best would be to support older versions of gradle still:
https://github.com/melix/jmh-gradle-plugin/blob/a034aa88805b7a06fa9c5a825d573554b2aa23e2/src/main/groovy/me/champeau/gradle/JMHPlugin.groovy#L289-L296

**Comment by bjoernQ** [comment]
Thanks for your suggestion - sounds good. As long as it can be done while still supporting older Gradle versions it will be a nice improvement.

**Comment by drewhannay** [comment]
> use variants, get their compiler tasks provider and depend on it. It would remove the afterEvaluate clause that is a bit dirty

@stephanenicolas Any idea if it's possible to do this without adding a dependency on AGP?

**Comment by stephanenicolas** [comment]
I don't think it's possible, you need this dependency.

Le lun. 28 janv. 2019 à 11:16, Drew Hannay <notifications@github.com> a
écrit :

**Comment by drewhannay** [comment]
Hm, that's unfortunate, since depending on a recent AGP version will also implicitly force a newer Gradle version. It also increases the maintenance cost on this project, given how often AGP makes breaking changes.

I wonder how bad it would be to make users hook up the task dependencies themselves instead of the plugin doing it?

**Comment by stephanenicolas** [comment]
Variants have been pretty stable in Android and most plugins use them.

There are a few problems with afterEvaluate blocks: they are hacky, provide
less control on when things are done, and in this case make it very hard to
debug and know that issues come from this plugin. The last point was really
very hard, I knew a plugin was doing too much and I didn't know which one,
I had to go through the source code of quite a few to find the problem here.

I didn't understand your question about the tasks, not precisely, but I
think it would be hard for devs
to hook up all tasks to their respective variants. And you would have to
provide how to do it anyway
as part of the documentation.

The new lazy task creation API is just the right way to write a plugin now.
About the variants, I can
understand your concerns, but honnestly for an android plugin I believe
it's also the right way to do things.
Again, all plugins I know do that.

Le lun. 28 janv. 2019 à 12:10, Drew Hannay <notifications@github.com> a
écrit :

**Comment by drewhannay** [comment]
I completely agree that this project should use the new lazy task creation API, fwiw. :)

I was just trying to think about the best way to do it and minimize impact on maintenance and backwards compatibility. In my project, I've frequently found myself waiting on other plugins to adopt newer AGP APIs, which makes me hesitant to add another dependency in my app.

**Comment by stephanenicolas** [comment]
I understand your point, but as an android plugin, I would say that (y)our
options are limited.. ;)
And alternatives will not be as goods.

Le lun. 28 janv. 2019 à 15:45, Drew Hannay <notifications@github.com> a
écrit :

**Comment by stephanenicolas** [comment]
@drewhannay here is a PR solving the issue. Let me know if you like it.

**Comment by bjoernQ** [comment]
merged and released
