### ISSUE TITLE
Publish on main jcenter

### ISSUE THREAD

**Issue by stephanenicolas** [bjoernQ/unmock-plugin#55]
Hi @bjoernQ , 

do you mind to publish you artifact of unmock 0.7.3 (and the next ones) on the main jcenter repo ?
At Groupon, we are using an internal nexus proxy, and it looks like for all small repos of bintray we have to create a small repo in our nexus. And this process is painful..

Do you mind to add your artifact there ? Personnally I deploy all my libraries on maven central, and they are cloned automatically by jcenter.

**Comment by bjoernQ** [comment]
Hello,

not sure if I understand the situation correctly.

It's available on http://jcenter.bintray.com/de/mobilej/unmock/UnMockPlugin/0.7.3/

What do you mean by main jcenter repo?

I avoided Maven Central because it seemed to be a bit more initial effort but maybe I should look into it again.

**Comment by stephanenicolas** [comment]
Hey Bjorn,

personnally I prefer to publish on jcenter, or main maven central, it's
just easier not to setup a repo per lib.
But up to you.

S.

Le sam. 11 mai 2019 à 06:28, Björn Quentin <notifications@github.com> a
écrit :

**Comment by bjoernQ** [comment]
Hi Stephane,

What do you mean by main jcenter repo? Isn't jcenter.bintray.com the main one? 

It's there (beside the private repo at https://dl.bintray.com/bjoernq/maven/de/mobilej/unmock/UnMockPlugin/ it's also at  http://jcenter.bintray.com/de/mobilej/unmock/UnMockPlugin/0.7.3/)

**Comment by stephanenicolas** [comment]
Yes, but http://jcenter.bintray.com/de/mobilej
<http://jcenter.bintray.com/de/mobilej/unmock/UnMockPlugin/0.7.3/> is not.
Maybe the only way to publish to jcenter-jcenter is through maven central,
not sure..

Le dim. 12 mai 2019 à 02:04, Björn Quentin <notifications@github.com> a
écrit :

**Comment by bjoernQ** [comment]
That's odd - I get the plugin at the link you posted:

<img width="740" alt="Bildschirmfoto 2019-05-12 um 12 06 39" src="https://user-images.githubusercontent.com/5682593/57580804-879f3400-74ae-11e9-9e2d-4c115dd2977f.png">
