### ISSUE TITLE
Could not find method register()

### ISSUE THREAD

**Issue by ebrowne72** [bjoernQ/unmock-plugin#57]
Unmock plugin v0.7.3

Getting the error "Could not find method register() for arguments [unMock, class de.mobilej.UnMockTask, de.mobilej.unmock.UnMockPlugin$_apply_closure2@11e9ad8c] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer."

Upgrading from 0.6.4 when I saw this problem.

Android Gradle plugin: 3.2.1
Gradle: 4.8
Kotlin: 1.3.31

**Comment by bjoernQ** [comment]
seems your Android Gradle plugin is too old - please try with a more recent version like 3.3.0

another option would be to downgrade the unmock version to something earlier than (not including) 0.7.1 - e.g. 0.7.0
