### ISSUE TITLE
default configuration

### ISSUE THREAD

**Issue by ligi** [bjoernQ/unmock-plugin#6]
would be great if the plugin falls back to a default configuration if none is given - most will use the same configuration and this would un-pollute the gradle files a bit

**Comment by bjoernQ** [comment]
nice idea, I'll consider adding this to the upcoming version. I'm just unsure if adding your own configuration should (by default) overwrite the default config or if it should be in addition to the default (and offer a way to "reset" the defaults).

**Comment by ligi** [comment]
I think it should overwrite the default config

**Comment by bjoernQ** [comment]
Just release 0.3.5 which does exactly this - please have a look and close this issue if it works for you.

**Comment by ligi** [comment]
Great! Will do - could take a bit as I am on the the chaos communication camp

**Comment by ligi** [comment]
looks good! thanks
