### ISSUE TITLE
unMock gradle task won't run automatically for library module

### ISSUE THREAD

**Issue by Piasy** [bjoernQ/unmock-plugin#7]
When run `gradle :libModule:test`, the unMock gradle task won't run automatically.
But run `gradle :libModule:unMock :libModule:test`, everything works perfect.

**Comment by bjoernQ** [comment]
Seems the problem there wasn't the library project but Android Gradle plugin 1.3.0. This (and more) is now fixed in version 0.3.3. Just update the dependency and it should work.

Thanks! If it works for you please close this issue.

**Comment by Piasy** [comment]
Everything works perfect! Thanks!

**Comment by lomza** [comment]
@bjoernQ , could you please confirm that the latest **unmock-plugin** version (0.5.1) works with Gradle (2.13) ? I have created an Android project (app) and unmock works perfectly fine there, BUT when using in library module, unMock section in Gradle has no effect at all. I suspect it got broken again?

**Comment by Piasy** [comment]
I have no problem with unmock 0.5.1, gradle 2.14.1 and 3.1, android gradle build tool 2.2.2.

**Comment by lomza** [comment]
OK, thanks! Turns out I had 0.5.0 of unmock and it doesn't work there, but works fine with 0.5.1 (gradle 2.14.1 and AS 2.2.2)  ;)
