### ISSUE TITLE
Version 0.7.8 is not on mvnrepository

### ISSUE THREAD

**Issue by lsrom** [bjoernQ/unmock-plugin#74]
Latest version cannot be found on mvnrepository and previous available (0.7.6) reports gradle issues which should be fixed in new version. Can you upload new version to mvn please?

**Comment by bjoernQ** [comment]
Hello!

0.7.8 is available on Central: https://github.com/bjoernQ/unmock-plugin/issues/70#issuecomment-818958244

Please note that the the group id had to change in order to get it to Central - the new artifact id is `com.github.bjoernq:unmockplugin:0.7.6`

**Comment by lsrom** [comment]
Thanks, I now see it in the README as well. Might be worth to update it though to make it clear that the old ID is no longer updated.
