### ISSUE TITLE
Gradle 7.0 migration issue

### ISSUE THREAD

**Issue by msimar** [bjoernQ/unmock-plugin#75]
```
Some problems were found with the configuration of task ':app:unMock' (type 'UnMockTask').
  - Type 'de.mobilej.UnMockTask' property 'outputDir' is annotated with @PathSensitive but that is not allowed for 'OutputDirectory' properties.
    
    Reason: This modifier is used in conjunction with a property of type 'OutputDirectory' but this doesn't have semantics.
    
    Possible solution: Remove the '@PathSensitive' annotation.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#incompatible_annotations for more details about this problem.
  - Type 'de.mobilej.UnMockTask' property 'unmockedOutputJar' is annotated with @PathSensitive but that is not allowed for 'OutputFile' properties.
    
    Reason: This modifier is used in conjunction with a property of type 'OutputFile' but this doesn't have semantics.
    
    Possible solution: Remove the '@PathSensitive' annotation.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#incompatible_annotations for more details about this problem.

```

Possible solution remove line https://github.com/bjoernQ/unmock-plugin/blob/70e921c03d4e1484bbc597ff36e05c82637d61be/buildSrc/src/main/java/de/mobilej/UnMockTask.java#L57

**Comment by bjoernQ** [comment]
Hello!

That's already fixed in #71 - please note that the group id is changed for the latest releases available on Maven Central (see #74)

**Comment by msimar** [comment]
@bjoernQ I'm still having same issue - we should remove annotation @PathSensitive to make it compatible with 7.0.0 gradle.

**Comment by bjoernQ** [comment]
that's really strange since 0.7.8 is built from current `master` branch where those annotations are removed
maybe some hick-up with the Gradle caches?

**Comment by Bubu** [comment]
Just wanted to note, that I ran into this as well today, but for me updating the plugin version to latest (0.7.8) did indeed fix it.

**Comment by msimar** [comment]
@bjoernQ there was some hiccup with the gradle cache, all looks good now, thanks.
